import { User } from 'firebase/auth';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useContext, useEffect, useState } from 'react';
import Header from '../components/header/Header';
import AuthContext from '../context/AuthContext';

const Home: NextPage = () => {
  const { currentUser } = useContext(AuthContext);
  const [jwtToken, setJwtToken] = useState<string>();

  useEffect(() => {
    currentUser?.getIdToken().then(setJwtToken);
  }, [currentUser, setJwtToken]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <h1 className="text-3xl italic text-rose-500 bg-amber-300 rounded-md p-2">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className="space-y-4">{displayUserInfo(currentUser)}</div>
        <div className="space-y-4 p-8">
          <div className="break-all">{jwtToken || 'JWT token not found'}</div>
          <p>
            Check out the JWT token at{' '}
            <a className="text-sky-500" href="https://jwt.io">
              jwt.io
            </a>
          </p>
        </div>
      </main>
    </div>
  );
};

function displayUserInfo(user: User | undefined) {
  if (!user) return <>Failed to get user!</>;

  const githubProviderData = user.providerData.length != 0 ? user.providerData[0] : null;
  return (
    <>
      <p>Logged in as UID {user?.uid}</p>
      {githubProviderData?.photoURL ? (
        <div className="flex space-x-4">
          <p>Github Provider Data:</p>
          <img src={githubProviderData.photoURL} alt="Github Profile Photo" width="30"></img>
          <p>{githubProviderData.email}</p>
        </div>
      ) : (
        <p>Not signed in to github</p>
      )}
    </>
  );
}

export default Home;
